### PR TITLE
Add quick try Colab Notebook

### PR DESCRIPTION
**Pull request by sunyuhan19981208**
I provide a colab notebook which can quick try chinese llama in gradio demo.
Here is the url of the colab notebook: https://colab.research.google.com/drive/1mG8CwGub-hcoeo79FjfoWtxqOuu3P_y1?usp=sharing

截屏2023-05-17 下午5 02 40

### CODE REVIEW

**Comment by airaria** [comment]
Would you mind if I copy and put your Colab notebook into the repo, so that the repo is self-contained?

**Comment by sunyuhan19981208** [comment]
> Would you mind if I copy and put your Colab notebook into the repo, so that the repo is self-contained?

Sure, you are welcome to copy and include the Colab notebook in your repository to make it self-contained.

**Comment by airaria** [comment]
There are html tags around the text:
screencast

Is there a way to remove them?
@sunyuhan19981208

**Comment by sunyuhan19981208** [comment]
> After I click the submit, html tags are added to the texts (The input is "你好"): screencast
> 
> Is there a way to remove them? @sunyuhan19981208

I think there is, I will try to fix that.

**Comment by sunyuhan19981208** [comment]
> After I click the submit, html tags are added to the texts (The input is "你好"): screencast
> 
> Is there a way to remove them? @sunyuhan19981208

截屏2023-05-29 上午11 52 38
I can't reproduce it...

**Comment by airaria** [comment]
@sunyuhan19981208  My colleague and I can both reproduce the problem with the notebook link you gave https://colab.research.google.com/drive/1mG8CwGub-hcoeo79FjfoWtxqOuu3P_y1?usp=sharing.  

We have tested Safari + MacOS, Chrome + MacOS, Chrome + Win11, Edge + Win11. What is your environment?

**Comment by sunyuhan19981208** [comment]
> @sunyuhan19981208 My colleague and I can both reproduce the problem with the notebook link you gave https://colab.research.google.com/drive/1mG8CwGub-hcoeo79FjfoWtxqOuu3P_y1?usp=sharing.
> 
> We have tested Safari + MacOS, Chrome + MacOS, Chrome + Win11, Edge + Win11. What is your environment?

I have successfully reproduced it using a Colab notebook, but I encountered difficulties when trying to reproduce it on my local server. It's quite weird, but I assure you that I am committed to finding a solution. I apologize for any inconvenience caused, and I will put in extra effort to resolve this issue. Thank you for your understanding and patience.

**Comment by airaria** [comment]
> > @sunyuhan19981208 My colleague and I can both reproduce the problem with the notebook link you gave https://colab.research.google.com/drive/1mG8CwGub-hcoeo79FjfoWtxqOuu3P_y1?usp=sharing.
> > We have tested Safari + MacOS, Chrome + MacOS, Chrome + Win11, Edge + Win11. What is your environment?
> 
> In the new commit [2ae52cb](https://github.com/ymcui/Chinese-LLaMA-Alpaca/commit/2ae52cb302ebb8896629571f85d3ebd1f6f00ee2) I delete the mdtex2html part, and then the chat message seems good.

It looks good now.

**Comment by airaria** [comment]
We temporarily merge the PR into `gradio_notebook` branch, and then merge it into the main branch after reorganizing some code and docs.

**Review by airaria — APPROVED** [review]

**Pull request merged**
